# Generated by Django 3.2.9 on 2021-11-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='arrived_time',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='dispatched_time',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
