# Generated by Django 3.2.9 on 2021-11-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20211125_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='arrived_date',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='dispatched_date',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
