# Generated by Django 3.2.9 on 2021-11-27 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20211125_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='authenticator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_secret', models.CharField(max_length=100)),
                ('claimed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
