# Generated by Django 3.2.9 on 2021-11-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_authenticator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claimed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_secret', models.CharField(max_length=100)),
            ],
        ),
    ]
